### ISSUE TITLE
train/val_files.txt for training on other datasets

### ISSUE THREAD

**Issue by yeonkyeong-lee** [harlanhong/Face-Depth-Network#2]
Hi, thank you for your great work. 
I want to train Face Depth Network on my dataset, but there seems to need train/val_files.txt to train the network. Could you share the code snippet that is used to generate train/val_files.txt?

**Comment by harlanhong** [comment]
You can refer to this:
`def produce_txt_list_vox1():
    train_num = 0
    test_num = 0
    train = True
    if train: 
        videos = glob.glob('/data/fhongac/origDataset/vox1_frames/train/*')
        trainfile = open('./vox1/train_files.txt', 'w', encoding='UTF-8')
    else:
        videos = glob.glob('/data/fhongac/origDataset/vox1_frames/test/*')
        testfile = open('./vox1/val_files.txt', 'w', encoding='UTF-8')
    for v in videos:
        print(v)
        if train:
            imgs = os.listdir(v)
            num = len(imgs)
            if num<=2:
                continue
            imglist = range(2,num-1)
            choice = random.sample(imglist,int(num/3))
            for ch in choice:
                string = v+' '+str(ch)+'\n'
                trainfile.write(string)
                train_num+=1
        else:
            imgs = os.listdir(v)
            num = len(imgs)
            if num<=2:
                continue
            imglist = range(2,num-1)
            choice = random.sample(imglist,int(num/3))
            for ch in choice:
                string = v+' '+str(ch)+'\n'
                testfile.write(string)
                test_num+=1
            if test_num>1000:
                testfile.close()
    trainfile.close()`

**Comment by harlanhong** [comment]
Please refer to this file: https://github.com/harlanhong/Face-Depth-Network/blob/master/celeb_utils.py

**Comment by yeonkyeong-lee** [comment]
thank you!
